name: Minimal Android CI Workflow

on:
  push:
    branches:
      - deploy

jobs:
  apk:
    name: Build & Deploy APK
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Build APK
        run: sudo ./gradlew assembleDebug --stacktrace

      - name: store app version code
        run: sudo VERSION=$(sudo ./gradlew -q printVersionCode | tail -n 1)

      - name: print app version code
        run: sudo echo "$VERSION version"
  
      - name: Release APK
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "test release"
          files: "**.apk"
